-- ============================================================
-- BwVr Report Management System
-- FILE 1: 01_sequences.sql
-- Run as BWVR schema user
-- ============================================================

-- Reference Number Sequence (starts at 1000, zero-padded to REF-000001)
CREATE SEQUENCE BWVR.SEQ_REPORT_REF_NUM
  START WITH 1000
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

CREATE SEQUENCE BWVR.SEQ_TEMPLATE_ID
  START WITH 1
  INCREMENT BY 1
  NOCACHE;

CREATE SEQUENCE BWVR.SEQ_REPORT_ID
  START WITH 1
  INCREMENT BY 1
  NOCACHE;

CREATE SEQUENCE BWVR.SEQ_PLACEHOLDER_ID
  START WITH 1
  INCREMENT BY 1
  NOCACHE;

CREATE SEQUENCE BWVR.SEQ_REPORT_VALUE_ID
  START WITH 1
  INCREMENT BY 1
  NOCACHE;

CREATE SEQUENCE BWVR.SEQ_IMAGE_SLOT_ID
  START WITH 1
  INCREMENT BY 1
  NOCACHE;

CREATE SEQUENCE BWVR.SEQ_AUDIT_ID
  START WITH 1
  INCREMENT BY 1
  NOCACHE;

COMMIT;
