-- ============================================================
-- BwVr Report Management System
-- FILE 2: 02_tables_core.sql
-- Run as BWVR schema user after 01_sequences.sql
-- ============================================================

-- ============================================================
-- TABLE: BWVR_TEMPLATE
-- Stores uploaded report templates (one per bank + template name)
-- ============================================================
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE BWVR.BWVR_TEMPLATE CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/

CREATE TABLE BWVR.BWVR_TEMPLATE (
  TEMPLATE_ID         NUMBER(10)      NOT NULL,
  BANK_NAME           VARCHAR2(200)   NOT NULL,
  TEMPLATE_NAME       VARCHAR2(300)   NOT NULL,
  TEMPLATE_FILE_NAME  VARCHAR2(500)   NOT NULL,
  TEMPLATE_FILE_PATH  VARCHAR2(1000)  NOT NULL,
  TEMPLATE_VERSION    VARCHAR2(20)    DEFAULT '1.0' NOT NULL,
  IS_ACTIVE           CHAR(1)         DEFAULT 'Y' NOT NULL,
  PARSED_STATUS       VARCHAR2(20)    DEFAULT 'PENDING' NOT NULL,
  CREATED_BY          VARCHAR2(100)   NOT NULL,
  CREATED_AT          TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_BY          VARCHAR2(100),
  UPDATED_AT          TIMESTAMP,
  TEMPLATE_CONTENT    BLOB,
  CONSTRAINT PK_BWVR_TEMPLATE PRIMARY KEY (TEMPLATE_ID),
  CONSTRAINT UQ_TEMPLATE_BANK_NAME UNIQUE (BANK_NAME, TEMPLATE_NAME),
  CONSTRAINT CK_TPL_IS_ACTIVE CHECK (IS_ACTIVE IN ('Y','N')),
  CONSTRAINT CK_TPL_PARSED_STATUS CHECK (PARSED_STATUS IN ('PENDING','PARSED','CONFIRMED','ERROR'))
);

COMMENT ON TABLE  BWVR.BWVR_TEMPLATE IS 'Stores metadata for each uploaded report template.';
COMMENT ON COLUMN BWVR.BWVR_TEMPLATE.TEMPLATE_ID        IS 'Surrogate PK. From SEQ_TEMPLATE_ID.';
COMMENT ON COLUMN BWVR.BWVR_TEMPLATE.BANK_NAME          IS 'Bank the template is associated with.';
COMMENT ON COLUMN BWVR.BWVR_TEMPLATE.PARSED_STATUS      IS 'PENDING=not parsed, PARSED=extracted, CONFIRMED=user confirmed, ERROR=parse failed.';

-- ============================================================
-- TABLE: BWVR_TEMPLATE_PLACEHOLDER
-- Each placeholder found in a template, with its question form
-- ============================================================
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE BWVR.BWVR_TEMPLATE_PLACEHOLDER CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/

CREATE TABLE BWVR.BWVR_TEMPLATE_PLACEHOLDER (
  PLACEHOLDER_ID      NUMBER(10)      NOT NULL,
  TEMPLATE_ID         NUMBER(10)      NOT NULL,
  PLACEHOLDER_KEY     VARCHAR2(300)   NOT NULL,
  PLACEHOLDER_PREFIX  VARCHAR2(20)    NOT NULL,
  DISPLAY_LABEL       VARCHAR2(500)   NOT NULL,
  QUESTION_TEXT       VARCHAR2(1000)  NOT NULL,
  FIELD_TYPE          VARCHAR2(50)    NOT NULL,
  IS_REQUIRED         CHAR(1)         DEFAULT 'Y' NOT NULL,
  DISPLAY_ORDER       NUMBER(5)       NOT NULL,
  TABLE_CONTEXT       VARCHAR2(500),
  COL1_HEADER         VARCHAR2(500),
  COL2_HEADER         VARCHAR2(500),
  SECTION_NAME        VARCHAR2(500),
  IS_CONFIRMED        CHAR(1)         DEFAULT 'N' NOT NULL,
  CREATED_AT          TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_BWVR_TEMPLATE_PH PRIMARY KEY (PLACEHOLDER_ID),
  CONSTRAINT FK_TPH_TEMPLATE FOREIGN KEY (TEMPLATE_ID) REFERENCES BWVR.BWVR_TEMPLATE(TEMPLATE_ID) ON DELETE CASCADE,
  CONSTRAINT CK_TPH_PREFIX CHECK (PLACEHOLDER_PREFIX IN ('TEXT','DATE','IMG','NUMBER','SELECT')),
  CONSTRAINT CK_TPH_IS_REQUIRED CHECK (IS_REQUIRED IN ('Y','N')),
  CONSTRAINT CK_TPH_IS_CONFIRMED CHECK (IS_CONFIRMED IN ('Y','N'))
);

COMMENT ON TABLE  BWVR.BWVR_TEMPLATE_PLACEHOLDER IS 'Stores every placeholder detected in a template .docx file.';
COMMENT ON COLUMN BWVR.BWVR_TEMPLATE_PLACEHOLDER.PLACEHOLDER_KEY    IS 'Exact placeholder string including << and >> delimiters.';
COMMENT ON COLUMN BWVR.BWVR_TEMPLATE_PLACEHOLDER.TABLE_CONTEXT      IS 'Encoded position when inside a table: T{n}_R{r}_C{c}.';

-- ============================================================
-- TABLE: BWVR_TEMPLATE_IMAGE_SLOT
-- Image placeholder positions and captured dimensions
-- ============================================================
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE BWVR.BWVR_TEMPLATE_IMAGE_SLOT CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/

CREATE TABLE BWVR.BWVR_TEMPLATE_IMAGE_SLOT (
  IMAGE_SLOT_ID       NUMBER(10)      NOT NULL,
  TEMPLATE_ID         NUMBER(10)      NOT NULL,
  PLACEHOLDER_KEY     VARCHAR2(300)   NOT NULL,
  ORIGINAL_WIDTH_EMU  NUMBER(12),
  ORIGINAL_HEIGHT_EMU NUMBER(12),
  WIDTH_PIXELS        NUMBER(6),
  HEIGHT_PIXELS       NUMBER(6),
  WIDTH_INCHES        NUMBER(8,4),
  HEIGHT_INCHES       NUMBER(8,4),
  PAGE_POSITION       VARCHAR2(100),
  CREATED_AT          TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_BWVR_IMG_SLOT PRIMARY KEY (IMAGE_SLOT_ID),
  CONSTRAINT FK_IMGSLOT_TEMPLATE FOREIGN KEY (TEMPLATE_ID) REFERENCES BWVR.BWVR_TEMPLATE(TEMPLATE_ID) ON DELETE CASCADE
);

COMMENT ON TABLE  BWVR.BWVR_TEMPLATE_IMAGE_SLOT IS 'Image positions and EMU dimensions from template .docx.';
COMMENT ON COLUMN BWVR.BWVR_TEMPLATE_IMAGE_SLOT.ORIGINAL_WIDTH_EMU IS 'EMU width. 914400 EMU = 1 inch.';

COMMIT;
