-- ============================================================
-- BwVr Report Management System
-- FILE 3: 03_tables_report.sql
-- Run as BWVR schema user after 02_tables_core.sql
-- ============================================================

-- ============================================================
-- TABLE: BWVR_REPORT
-- Master record for each generated report instance
-- ============================================================
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE BWVR.BWVR_REPORT CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/

CREATE TABLE BWVR.BWVR_REPORT (
  REPORT_ID           NUMBER(10)      NOT NULL,
  REFERENCE_NUMBER    VARCHAR2(30)    NOT NULL,
  TEMPLATE_ID         NUMBER(10)      NOT NULL,
  REPORT_TITLE        VARCHAR2(500)   NOT NULL,
  VENDOR_NAME         VARCHAR2(300),
  LOCATION            VARCHAR2(300),
  BANK_NAME           VARCHAR2(200),
  REPORT_STATUS       VARCHAR2(30)    DEFAULT 'DRAFT' NOT NULL,
  GENERATED_FILE_PATH VARCHAR2(1000),
  GENERATED_AT        TIMESTAMP,
  CREATED_BY          VARCHAR2(100)   NOT NULL,
  CREATED_AT          TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_BY          VARCHAR2(100),
  UPDATED_AT          TIMESTAMP,
  IS_DELETED          CHAR(1)         DEFAULT 'N' NOT NULL,
  DELETED_AT          TIMESTAMP,
  DELETED_BY          VARCHAR2(100),
  CONSTRAINT PK_BWVR_REPORT PRIMARY KEY (REPORT_ID),
  CONSTRAINT UQ_REPORT_REFNUM UNIQUE (REFERENCE_NUMBER),
  CONSTRAINT FK_REPORT_TEMPLATE FOREIGN KEY (TEMPLATE_ID) REFERENCES BWVR.BWVR_TEMPLATE(TEMPLATE_ID),
  CONSTRAINT CK_REPORT_STATUS CHECK (REPORT_STATUS IN ('DRAFT','IN_PROGRESS','COMPLETED','ARCHIVED')),
  CONSTRAINT CK_REPORT_IS_DELETED CHECK (IS_DELETED IN ('Y','N'))
);

CREATE INDEX IDX_REPORT_REFNUM    ON BWVR.BWVR_REPORT(REFERENCE_NUMBER);
CREATE INDEX IDX_REPORT_VENDOR    ON BWVR.BWVR_REPORT(VENDOR_NAME);
CREATE INDEX IDX_REPORT_LOCATION  ON BWVR.BWVR_REPORT(LOCATION);
CREATE INDEX IDX_REPORT_BANK      ON BWVR.BWVR_REPORT(BANK_NAME);
CREATE INDEX IDX_REPORT_ISDELETED ON BWVR.BWVR_REPORT(IS_DELETED);

COMMENT ON TABLE  BWVR.BWVR_REPORT IS 'Master report record. REFERENCE_NUMBER is the primary business identifier.';
COMMENT ON COLUMN BWVR.BWVR_REPORT.REFERENCE_NUMBER IS 'Format: REF-YYYYMMDD-{6-digit}. Immutable once created.';
COMMENT ON COLUMN BWVR.BWVR_REPORT.IS_DELETED       IS 'Soft delete flag. Y=deleted (hidden from UI).';

-- ============================================================
-- TABLE: BWVR_REPORT_VALUE
-- Stores each placeholder's user-supplied value
-- ============================================================
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE BWVR.BWVR_REPORT_VALUE CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/

CREATE TABLE BWVR.BWVR_REPORT_VALUE (
  VALUE_ID            NUMBER(10)      NOT NULL,
  REPORT_ID           NUMBER(10)      NOT NULL,
  PLACEHOLDER_ID      NUMBER(10)      NOT NULL,
  PLACEHOLDER_KEY     VARCHAR2(300)   NOT NULL,
  TEXT_VALUE          VARCHAR2(4000),
  IMAGE_FILE_PATH     VARCHAR2(1000),
  IMAGE_ORIGINAL_NAME VARCHAR2(500),
  IMAGE_DATA          BLOB,
  CREATED_AT          TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT          TIMESTAMP,
  CONSTRAINT PK_BWVR_REPORT_VALUE PRIMARY KEY (VALUE_ID),
  CONSTRAINT FK_RV_REPORT FOREIGN KEY (REPORT_ID) REFERENCES BWVR.BWVR_REPORT(REPORT_ID) ON DELETE CASCADE,
  CONSTRAINT FK_RV_PLACEHOLDER FOREIGN KEY (PLACEHOLDER_ID) REFERENCES BWVR.BWVR_TEMPLATE_PLACEHOLDER(PLACEHOLDER_ID),
  CONSTRAINT UQ_RV_REPORT_PH UNIQUE (REPORT_ID, PLACEHOLDER_ID)
);

COMMENT ON TABLE  BWVR.BWVR_REPORT_VALUE IS 'User-entered value per placeholder per report. One row per placeholder.';
COMMENT ON COLUMN BWVR.BWVR_REPORT_VALUE.TEXT_VALUE      IS 'Text/number/date values. Dates as ISO-8601: YYYY-MM-DD.';
COMMENT ON COLUMN BWVR.BWVR_REPORT_VALUE.IMAGE_FILE_PATH IS 'Server path to uploaded image binary.';

COMMIT;
