-- ============================================================
-- BwVr Report Management System
-- FILE 5: 05_views.sql
-- ============================================================

-- Full report details with template info
CREATE OR REPLACE VIEW BWVR.VW_REPORT_DETAIL AS
SELECT
  r.REPORT_ID,
  r.REFERENCE_NUMBER,
  r.REPORT_TITLE,
  r.VENDOR_NAME,
  r.LOCATION,
  r.BANK_NAME,
  r.REPORT_STATUS,
  r.GENERATED_FILE_PATH,
  r.GENERATED_AT,
  r.CREATED_BY,
  r.CREATED_AT,
  r.IS_DELETED,
  t.TEMPLATE_NAME,
  t.TEMPLATE_FILE_NAME,
  (SELECT COUNT(*) FROM BWVR.BWVR_REPORT_VALUE rv WHERE rv.REPORT_ID = r.REPORT_ID) AS VALUES_COUNT,
  (SELECT COUNT(*) FROM BWVR.BWVR_TEMPLATE_PLACEHOLDER tp WHERE tp.TEMPLATE_ID = t.TEMPLATE_ID) AS TOTAL_PLACEHOLDERS
FROM BWVR.BWVR_REPORT r
JOIN BWVR.BWVR_TEMPLATE t ON r.TEMPLATE_ID = t.TEMPLATE_ID
WHERE r.IS_DELETED = 'N';

-- Template summary with placeholder counts
CREATE OR REPLACE VIEW BWVR.VW_TEMPLATE_SUMMARY AS
SELECT
  t.TEMPLATE_ID,
  t.BANK_NAME,
  t.TEMPLATE_NAME,
  t.TEMPLATE_VERSION,
  t.PARSED_STATUS,
  t.IS_ACTIVE,
  t.CREATED_AT,
  COUNT(tp.PLACEHOLDER_ID)                                        AS PLACEHOLDER_COUNT,
  COUNT(CASE WHEN tp.PLACEHOLDER_PREFIX = 'IMG'  THEN 1 END)    AS IMAGE_COUNT,
  COUNT(CASE WHEN tp.PLACEHOLDER_PREFIX = 'DATE' THEN 1 END)    AS DATE_COUNT,
  COUNT(CASE WHEN tp.PLACEHOLDER_PREFIX = 'TEXT' THEN 1 END)    AS TEXT_COUNT
FROM BWVR.BWVR_TEMPLATE t
LEFT JOIN BWVR.BWVR_TEMPLATE_PLACEHOLDER tp ON t.TEMPLATE_ID = tp.TEMPLATE_ID
WHERE t.IS_ACTIVE = 'Y'
GROUP BY t.TEMPLATE_ID, t.BANK_NAME, t.TEMPLATE_NAME, t.TEMPLATE_VERSION,
         t.PARSED_STATUS, t.IS_ACTIVE, t.CREATED_AT;

COMMIT;
